[package]
name = "flowsurface"
version = "0.6.0"
edition = "2024"
readme = "README.md"
license = "GPL-3.0-or-later"
categories = ["finance", "visualization", "gui"]
repository = "https://github.com/akenshaw/flowsurface"

[workspace]
members = ["exchanges"]

[workspace.dependencies]
iced_futures = "0.13.2"
chrono = "0.4.38"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"
log = "0.4.22"
thiserror = "1.0.68"
ordered-float = "4.5.0"
regex = "1.11.1"

[dependencies]
iced = { version = "0.14.0-dev", default-features = false, features = ["wgpu", "canvas", "tokio", "advanced", "lazy"] }
iced_futures.workspace = true
chrono.workspace = true
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
ordered-float.workspace = true
regex.workspace = true
log.workspace = true
rust_decimal = "1.36.0"
fern = "0.6.2"
dirs-next = "2.0.0"
uuid = { version = "1.11.0", features = ["v4"] }

exchanges = { version = "0.1.0", path = "exchanges" }

rithmic-client = { git = "https://github.com/pcortellezzi/rithmic-rs", rev = "f0d34eb8a4cac557c6b80d683f2835878d8fe7e9" }

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "beddf49c76f3b43e7b33452831e1293cad28fd89" }